// Automatically generated by SynthOS
// Declarations of synthesized code and data.
#ifndef SYNTHOS_GLOBALS_INCLUDED
#define SYNTHOS_GLOBALS_INCLUDED
#include "SynthOS_Kernel.h"
extern struct SynthOS_TCB SynthOS_tcb_notmain;

// User globals
extern void SynthOS_initScheduler();
extern void SynthOS_panic();
#endif
