// Automatically generated by SynthOS
// Definitions of synthesized code and data.
#include "SynthOS_globals.h"

struct SynthOS_TCB SynthOS_tcb_notmain;

// Initialize data structures synthesized for user code
void SynthOS_init() {
    SynthOS_initScheduler();
}

void SynthOS_panic() {
    // What should go here?
}
