// Automatically generated by SynthOS
#ifndef SYNTHOS_CONFIG_INCLUDED
#define SYNTHOS_CONFIG_INCLUDED
// Defines system parameters and macros.

// Interrupts:
#define SynthOS_lock SynthOS_nullLock
#define SynthOS_unlock SynthOS_nullUnlock
#define SynthOS_enableInterrupts SynthOS_nullEnableInterrupts

// Messages for call tasks:
#define SYNTHOS_SYSTEM_MESSAGES 0

#endif
